### ISSUE TITLE
Support for extent specifier?

### ISSUE THREAD

**Issue by EelhandsMcCoy** [alexwiese/EntityFrameworkCore.OpenEdge#13]
Hi. Since Progress supports array types with a field value, called "Extent," I have a decimal? array type that gets scaffolded as just plain decimal?, which causes queries to fail, listing the actual datatype as string. Is it possible to support this data type specification on the provider level, so the columns could be correctly scaffolded as decimal? [] ?

**Comment by alexwiese** [comment]
Hi,

Just looking at this, the SQL syntax for selecting those fields is as follows

SELECT monthquota[4] FROM pub.table

OR

SELECT monthquota__4 FROM pub.table

So in that case, to get it working now without any changes to the provider, you should be able to add the following properties to your entity class (replacing monthquota with whatever your field name is).

[Column("monthquota__1")]
public decimal MonthQuota1 { get;set; }

[Column("monthquota__2")]
public decimal MonthQuota2 { get;set; }

[Column("monthquota__3")]
public decimal MonthQuota3 { get;set; }

[Column("monthquota__4")]
public decimal MonthQuota4 { get;set; }

public decimal[] MonthQuota => new [] { MonthQuota1, MonthQuota2, MonthQuota3, MonthQuota4 };


To support the first syntax, and have a single array property would be a fair amount of work I would expect, as EF Core doesn't have a built-in concept of array types/extents/indexers. It can handle byte[] but that's because it just gets mapped to a single binary data column; ie. you can't actually use the indexer to access a specific byte/value.
It might not even be possible without changes to EF Core itself.
The provider most likely would have to do some magic to change the mapping of the query result so that the monthquota__xyz columns would get combined into a single field.

Thanks,
Alex
________________________________

**Comment by EelhandsMcCoy** [comment]
Thank you, this worked for my issue. Only thing to note is the syntax changed for the progress version I am using, 11.something uses columnName[index] instead of __index.
