### ISSUE TITLE
[OPENEDGE]Column "TIMESTAMP" cannot be found or is not specified for query.

### ISSUE THREAD

**Issue by CarlosArmiliato** [alexwiese/EntityFrameworkCore.OpenEdge#15]
When i'm add date time filter, the SQL was be generated with "TIMESTAMP" literal before date value.
Like:
... WHERE DtCreate <= TIMESTAMP '2020-05-01 00:00:00.0000000' ...

And OpenEdge returns.
[OPENEDGE]Column "TIMESTAMP" cannot be found or is not specified for query.

In my domain, this is a DateTime property.
In Progress Database this is Date field.

I'm using version 1.0.8 of this library and EF Core 2.2.6

What I need SQL will be generated without "TIMESTAMP" for?
Like: ... WHERE DtCreate <= '2020-05-01 00:00:00.0000000' ...

**Comment by alexwiese** [comment]
Hi @CarlosArmiliato 

I was able reproduce your issue.
The problem seems to come about when EF Core tries to map the creation of the DateTime value to the TIMESTAMP function in SQL (which is not available in OpenEdge).
This should be fixed in the provider but for now you can workaround it by not materializing the DateTime in the actual query itself. 

For example change this

```
	context.Tests
		.Where(t => t.datetime_field <= new DateTime(2021, 01, 01))
		.ToList()
```

To this

```
	var dateTime = new DateTime(2021, 01, 01);
	context.Tests
		.Where(t => t.datetime_field <= dateTime)
		.ToList()
```

This will prevent EF Core adding the TIMESTAMP function to the generated query.

**Comment by CarlosArmiliato** [comment]
Thanks Alex,
When I get to work tomorrow, I take this test.
I'm not a .Net expert, but if you know where the error is, I try to fix it.
I already cloned and debugged your library today, but I didn't find the problem.

I'm open issue #14

**Comment by CarlosArmiliato** [comment]
I Alex, i'm closing this issue because I use another framework in my project.
The bug is in that framework.

**Comment by fabianffrank** [comment]
In some simple cases the workaround worked for me but in many cases it didn't. Beyond that it would be better if we would not need the workaround and could support the OpenEdge syntax for `DateTime` constants.
